apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: avs-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack  # Ensure this matches the Helm release name
spec:
  selector:
    matchLabels:
      app: avs-gke-aerospike-vector-search
  namespaceSelector:
    matchNames:
      - avs
  endpoints:
    - port: manage-5040
      path: /manage/rest/v1/prometheus
      interval: 15s
