version: "3.9"

networks:
  svc:
    name: svc

services:
  aerospike-cluster:
    image: aerospike/aerospike-server-enterprise:7.0.0.5
    container_name: "aerospike-cluster"
    command: --config-file /etc/aerospike/aerospike.conf
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ${PWD}/config:/etc/aerospike
    healthcheck:
      test: [ "CMD", "asinfo", "-p", "3000", "-v", "build" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - svc

  aerospike-vector-search:
    image: aerospike/aerospike-vector-search:0.11.1
    container_name: "aerospike-vector-search"
    depends_on:
      aerospike-cluster:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "5040:5040"
    volumes:
      - ${PWD}/config:/etc/aerospike-vector-search
    healthcheck:
      test: ["CMD", "curl", "-f", "http://aerospike-vector-search:5040/manage/rest/v1"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - svc

# Services used to monitor the Aerospike Vector Search cluster.
# This collects basic usage metrics so that Aerospike can better understand AVS is being used.
# If you would like to disable this, you can remove the following services.

  update-targets:
    image: python:3.9-alpine
    volumes:
      - ../.internal/metrics/scripts/update_targets.py:/scripts/update_targets.py
      - ../.internal/metrics/config:/config
    entrypoint: ["sh", "-c", "python3 /scripts/update_targets.py"]
    networks:
      - svc

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ../.internal/metrics/config:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      update-targets:
        condition: service_completed_successfully
      aerospike-vector-search:
        condition: service_healthy
    networks:
      - svc
