# This file is used to define the services that will
# be used to monitor the Aerospike Vector Search cluster.
# It is not meant to be used on its own but included in a
# docker compose file that defines the aerospike-vector-search service.

services:
  update-targets:
    image: python:3.9-alpine
    volumes:
      - ./scripts/update_targets.py:/scripts/update_targets.py
      - ./config:/config
    entrypoint: ["sh", "-c", "python3 /scripts/update_targets.py"]

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./config:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      update-targets:
        condition: service_completed_successfully
      aerospike-vector-search:
        condition: service_healthy