services:
  aerospike:
    image: aerospike/aerospike-server-enterprise:7.0.0.2
    # ports:
    #   - "3000:3000"
    networks:
      - avs-demo
    volumes:
      - ./container-volumes/aerospike/etc/aerospike:/opt/aerospike/etc/aerospike
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike/aerospike.conf"
      # use this line to store all index and vector data in the default namespace (test)
      # - "/opt/aerospike/etc/aerospike/aerospike-single-namespace.conf"
    healthcheck:
#      test: [ "CMD", "asinfo", "-U", "admin", "-P", "admin", "-p", "3000", "-v", "build" ]
      test: [ "CMD", "asinfo", "-p", "3000", "-v", "build" ]
      interval: 5s
      timeout: 20s
      retries: 10
  avs:
    depends_on:
      aerospike:
        condition: service_healthy
    image: aerospike/aerospike-vector-search:0.9.0
    # ports:
    #   - "5002:5002"
    networks:
      - avs-demo
    volumes:
      - ./container-volumes/avs/etc/aerospike-vector-search:/etc/aerospike-vector-search
    healthcheck:
      test: ["CMD", "curl", "-f", "http://avs:5040/manage/rest/v1"]
      interval: 5s
      timeout: 20s
      retries: 10
  app:
    image: quote-search
    depends_on:
      avs:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - avs-demo
    volumes:
      - ./container-volumes/quote-search/data:/container-volumes/quote-search/data
    environment:
      AVS_HOST: avs
      AVS_PORT: "5000"
      APP_NUM_QUOTES: "5000"
      GRPC_DNS_RESOLVER: native

networks:
  avs-demo: {}