services:
  aerospike:
    image: aerospike/aerospike-server-enterprise:7.0.0.2
    # ports:
      # - "3000:3000"
    networks:
      - proximus-demo
    volumes:
      - ./container-volumes/aerospike:/opt/aerospike/etc/aerospike
    mem_limit: 8g
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike/aerospike.conf"
  # prometheus-exporter:
  #   image: aerospike/aerospike-prometheus-exporter:latest
  #   environment:
  #     - AS_HOST=aerospike
  #   ports:
  #     - 9145:9145
  #   networks:
  #     - proximus-demo
  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     # - type: bind
  #     #   source: ./prometheus/prometheus.yml
  #     #   target: /etc/prometheus/prometheus.yml
  #     - ./prometheus/:/etc/prometheus/
  #     - prometheus_data:/prometheus
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - proximus-demo
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3003:3000"
  #   networks:
  #     - proximus-demo
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  proximus:
    image: aerospike.jfrog.io/docker/aerospike/aerospike-proximus-private:0.2.0
    networks:
      - proximus-demo
    volumes:
      - ./container-volumes/proximus:/etc/aerospike-proximus
  app:
    image: prism
    ports:
      - "8080:8080"
    networks:
      - proximus-demo
    environment:
      - PROXIMUS_HOST=proximus
      - PROXIMUS_PORT=5000
      - GRPC_DNS_RESOLVER=native
    volumes:
      - ./container-volumes/prism/images:/prism/static/images/data

  
networks:
  proximus-demo: {}

volumes:
 grafana-storage: {}
 prometheus_data: {}
 app_data: {}