services:
  aerospike:
    image: aerospike/aerospike-server-enterprise:7.0.0.2
    ports:
      - "3000:3000"
    networks:
      - avs-demo
    volumes:
      - ./container-volumes/aerospike/etc/aerospike:/opt/aerospike/etc/aerospike
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike/aerospike.conf"
  avs:
    image: aerospike/aerospike-vector-search:0.9.0
    networks:
      - avs-demo
    volumes:
      - ./container-volumes/avs/etc/aerospike-vector-search:/etc/aerospike-vector-search
  app:
    image: prism:latest
    ports:
      - "8080:8080"
    networks:
      - avs-demo
    environment:
      AVS_HOST: avs
      AVS_PORT: "5000"
      APP_NUM_QUOTES: "5000"
      GRPC_DNS_RESOLVER: native
    volumes:
      - ./container-volumes/prism/images:/prism/static/images/data

networks:
  avs-demo: {}
