services:
  aerospike:
    image: aerospike/aerospike-server-enterprise:7.0.0.2
    ports:
      - "3000:3000"
    networks:
      - proximus-demo
    volumes:
      - ./container-volumes/aerospike/etc/aerospike:/opt/aerospike/etc/aerospike
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike/aerospike.conf"
  proximus:
    image: aerospike/aerospike-proximus:0.3.1
    # ports:
      # - "5000:5000"
    networks:
      - proximus-demo
    volumes:
      - ./container-volumes/proximus/etc/aerospike-proximus:/etc/aerospike-proximus
  app:
    image: prism
    ports:
      - "8080:8080"
    networks:
      - proximus-demo
    environment:
      - PROXIMUS_HOST=proximus
      - PROXIMUS_PORT=5000
    volumes:
      - ./container-volumes/prism/images:/prism/static/images/data

networks:
  proximus-demo: {}
