replicaCount: 0 # must be set externally
aerospikeVectorSearchConfig:
  cluster:
    cluster-name: "avs-db-1"
  feature-key-file: "/etc/aerospike-vector-search/secrets/features.conf"
  service:
    metadata-namespace: "avs-meta"
    ports:
      5000:
        tls-id: service-tls
  manage:
    ports:
      5040: {}

  heartbeat:
    seeds:
      - address: avs-app-aerospike-vector-search-0.avs-app-aerospike-vector-search-internal.avs.svc.cluster.local
        port: 5001
  interconnect:
    client-tls-id: interconnect-tls
    ports:
      5001:
        addresses: "0.0.0.0"
        tls-id: interconnect-tls
  storage:
    client-policy:
      tls-id: aerospike-tls
      credentials:
        username: tester
        password-file: "/etc/aerospike-vector-search/secrets/aerospike-password.txt"
    seeds:
      - aerocluster-0-0.aerocluster.aerospike.svc.cluster.local:
          port: 4333
          tls-name: "asd.aerospike.com"
  security:
    auth-token:
      private-key: "/etc/aerospike-vector-search/secrets/private_key.pem"
      private-key-password: "/etc/aerospike-vector-search/secrets/client-password.txt"
      public-key: "/etc/aerospike-vector-search/secrets/public_key.pem"
  tls:
    service-tls:
      trust-store:
        store-file: /etc/ssl/certs/ca.aerospike.com.truststore.jks
        store-password-file: /etc/ssl/certs/storepass
        key-password-file: "/etc/ssl/certs/keypass"
      key-store:
        store-file: /etc/ssl/certs/svc.aerospike.com.keystore.jks
        store-password-file: /etc/ssl/certs/storepass
        key-password-file: /etc/ssl/certs/keypass
    #      override-tls-hostname: avs-app-aerospike-vector-search-0.avs-app-aerospike-vector-search.aerospike.svc.cluster.local

    interconnect-tls:
      trust-store:
        store-file: /etc/ssl/certs/ca.aerospike.com.truststore.jks
        store-password-file: /etc/ssl/certs/storepass
        key-password-file: "/etc/ssl/certs/keypass"
      key-store:
        store-file: /etc/ssl/certs/avs.aerospike.com.keystore.jks
        store-password-file: /etc/ssl/certs/storepass
        key-password-file: /etc/ssl/certs/keypass
      override-tls-hostname: avs.aerospike.com

    aerospike-tls:
      trust-store:
        store-file: "/etc/ssl/certs/ca.aerospike.com.truststore.jks"
        store-password-file: "/etc/ssl/certs/storepass"
        key-password-file: "/etc/ssl/certs/keypass"
      key-store:
        store-file: "/etc/ssl/certs/avs.aerospike.com.keystore.jks"
        store-password-file: "/etc/ssl/certs/storepass"
        key-password-file: "/etc/ssl/certs/keypass"
  #      override-tls-hostname: "asd.aerospike.com"

  logging:
    #    file: /var/log/aerospike-vector-search/aerospike-vector-search.log
    enable-console-logging: false
    format: simple
    max-history: 30
    levels:
      metrics-ticker: debug
      root: info
    ticker-interval: 10

serviceAccount:
  create: true

aerospikeVectorSearchNodeRoles:
  query-nodes:
    - query
  indexer-nodes:
    - index-update
  standalone-indexer-nodes:
    - standalone-indexer
  default-nodes:
    - query
    - index-update

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 0

## multiPodPerHost controls if connections will be made directly to the host. Some deployments might benefit from the default configuration and use NodePort
## for external access if it is needed.
## Only set multipodPerHost: false if this host networking is desired
multiPodPerHost: false
service:
  enabled: false
  type: ClusterIP
  ports:
    - name: "svc-port"
      port: 5000
      targetPort: 5000

initContainer:
  image:
    repository: aerospike.jfrog.io/container/avs-init-container
    pullPolicy: Always

image:
  repository: "aerospike/aerospike-vector-search"
  pullPolicy: "IfNotPresent"

extraSecretVolumeMounts:
  - name: aerospike-tls
    mountPath: "/etc/ssl/certs/"
    readOnly: true

extraVolumes:
  - name: aerospike-tls
    secret:
      secretName: aerospike-tls
      optional: false

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: aerospike.io/node-pool
              operator: In
              values:
                - "standalone-indexer-nodes"
                - "query-nodes"
                - "indexer-nodes"
                - "default-nodes"
                - "avs"
# podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       - topologyKey: "kubernetes.io/hostname"
#         labelSelector:
#           matchExpressions:
#             - key: "app.kubernetes.io/name"
#               operator: In
#               values:
#                 - "aerospike-vector-search"
