apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike

spec:
  size: 3
  image: aerospike/aerospike-server-enterprise:7.0.0.0
  storage:
    filesystemVolumePolicy:
      initMethod: deleteFiles
      cascadeDelete: true
    blockVolumePolicy:
      cascadeDelete: true
    volumes:
      - name: workdir
        aerospike:
          path: /opt/aerospike
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Filesystem
            size: 1Gi
      - name: proximus-meta
        aerospike:
          path: /proximus/dev/xvdf
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Block
            size: 20Gi

      - name: ns
        aerospike:
          path: /test/dev/xvdf
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Block
            size: 20Gi
      - name: aerospike-config-secret
        source:
          secret:
            secretName: aerospike-secret
        aerospike:
          path: /etc/aerospike/secret

  podSpec:
    sidecars:
    - name: aerospike-prometheus-exporter
      image: aerospike/aerospike-prometheus-exporter:v1.9.0
      ports:
        - containerPort: 9145
          name: exporter
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: aerospike.com/node-pool
              operator: In
              values:
              - "default-rack"
    multiPodPerHost: false

  # aerospikeAccessControl:
  #   users:
  #     - name: admin
  #       secretName: auth-secret
  #       roles:
  #         - sys-admin
  #         - user-admin

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
#    security: {}
    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002
    namespaces:
      - name: test
        replication-factor: 2
        storage-engine:
          type: device
          devices:
            - /test/dev/xvdf

      - name: proximus-meta
        nsup-period: 600
        nsup-threads: 2
        evict-tenths-pct: 5
        replication-factor: 2
        storage-engine:
          type: device
          devices:
            - /proximus/dev/xvdf