name: Build and Push Docker Images

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v4
      name: Checkout code
      with:
        fetch-depth: 1
        fetch-tags: true

    - name: Get release tag
      id: get-tag
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        fi
      shell: bash

  build-push-quote-search-preview:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push quote search preview Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./.internal/Dockerfile-quote-search-preview
        platforms: linux/amd64,linux/arm64
        push: true
        tags: aerospike/quote-search-example:preview

  build-push-quote-search:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push quote search Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./quote-semantic-search
        file: ./quote-semantic-search/Dockerfile-quote-search
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          aerospike/quote-search-example:latest
          aerospike/quote-search-example:${{ needs.setup.outputs.tag }}

  build-push-prism-search:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push prism search Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./quote-semantic-search
        file: ./quote-semantic-search/Dockerfile-prism
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          aerospike/prism-search-example:latest
          aerospike/prism-search-example:${{ needs.setup.outputs.tag }}